# Generated by Django 5.0.4 on 2024-04-17 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('grupo_tipo', models.CharField(choices=[('automovil', 'Automóvil'), ('camion', 'Camión'), ('camioneta', 'Camioneta'), ('moto', 'Moto'), ('otros', 'Otros')], max_length=20)),
                ('grupo_cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('tiempo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_vehiculos', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('automovil', 'Automóvil'), ('camion', 'Camión'), ('camioneta', 'Camioneta'), ('moto', 'Moto'), ('otros', 'Otros')], max_length=20)),
                ('direccion', models.CharField(choices=[('arriba', 'Arriba'), ('arriba-izquierda', 'Arriba-Izquierda'), ('arriba-derecha', 'Arriba-Derecha'), ('izquierda', 'Izquierda'), ('izquierda-arriba', 'Izquierda-Arriba'), ('derecha', 'Derecha'), ('derecha-arriba', 'Derecha-Arriba'), ('abajo', 'Abajo')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('tiempo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
