# Generated by Django 5.0.4 on 2024-04-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_paso', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('grupo_tipo', models.CharField(choices=[('automovil', 'Automóvil'), ('camion', 'Camión'), ('camioneta', 'Camioneta'), ('moto', 'Moto'), ('otros', 'Otros')], max_length=20)),
                ('grupo_cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('automovil', 'Automóvil'), ('camion', 'Camión'), ('camioneta', 'Camioneta'), ('moto', 'Moto'), ('otros', 'Otros')], max_length=20)),
                ('direccion', models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha'), ('arriba', 'Arriba'), ('abajo', 'Abajo')], max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
