# Generated by Django 5.0.4 on 2024-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='direccion',
            field=models.CharField(choices=[('arriba', 'Arriba'), ('arriba-izquierda', 'Arriba-Izquierda'), ('arriba-derecha', 'Arriba-Derecha'), ('izquierda', 'Izquierda'), ('izquierda-arriba', 'Izquierda-Arriba'), ('derecha', 'Derecha'), ('derecha-arriba', 'Derecha-Arriba'), ('abajo', 'Abajo')], max_length=20),
        ),
    ]
