# Generated by Django 5.0.4 on 2024-04-17 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=20)),
                ('tiempo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_vehiculos', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
