# Generated by Django 5.0.4 on 2024-04-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_incidentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentes',
            old_name='direccion',
            new_name='titulo',
        ),
    ]
