# Generated by Django 5.0.4 on 2024-04-13 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_alter_vehiculo_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='tiempo_paso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
